/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as DesignIdRouteImport } from './routes/design.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/design/',
  path: '/design/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design/$id': typeof DesignIdRoute
  '/design/': typeof DesignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design/$id': typeof DesignIdRoute
  '/design': typeof DesignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design/$id': typeof DesignIdRoute
  '/design/': typeof DesignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design/$id' | '/design/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design/$id' | '/design'
  id: '__root__' | '/' | '/design/$id' | '/design/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignIdRoute: typeof DesignIdRoute
  DesignIndexRoute: typeof DesignIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/design'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignIdRoute: DesignIdRoute,
  DesignIndexRoute: DesignIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
